# Ci de Nivel 01 - Disparo Manual atraves de clique

name: 'Execução Manual - Exercício 01'

# gatilhos / triggers - regra do dispoaro
# gatilho manual - workflow_dispatch

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

#tarefas dentro da piline = jobs

jobs:
  # job 1 - nome do job
  e2e-test:
    # ambiente de execução
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # passo 1 - nome do passo
      - name: 'Checkout do Código'
        uses: actions/checkout@v4

      # passo 2 - nome do passo
      - name: 'Configurar Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      # passo 3 - instalção do yarn
      - name: 'Instalar Dependências'
        run: npm install -g yarn

      # passo 4 - nome do passo
      - name: 'Instalar as dependencias do projeto'
        run: yarn

      - name: 'Intalando Browser do Playwright'
        run: yarn playwright install
      # passo 6 - Executar os testes E2E
      - name: 'Executar os Testes E2E'
        run: yarn run e2e

      - name: 'Publicar Relatorio dos Testes E2E'
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: 'Relatorio Playwright E2E'
          path: 'results.xml'
          reporter: 'java-junit'
          use-actions-summary: 'true'

#
